name: CI/CD Pipeline

# Trigger pipeline on push, pull_request, and manual workflow_dispatch
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Download Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check-6.5.3-release.zip -d dependency-check
          ls -alh dependency-check/

      - name: Ensure script is executable
        run: chmod +x ${GITHUB_WORKSPACE}/dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run Dependency Check
        run: |
          ${GITHUB_WORKSPACE}/dependency-check/dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --out . --format HTML --failOnCVSS 9 --disableAssembly || echo "Vulnerabilities found"

      # Step to verify file presence
      - name: List Files in Directory
        run: ls -alh .

      # Explicitly use v4 to upload the artifact
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html

  sast:
    needs: dependency-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Bandit Scan
        run: |
          pip install bandit
          bandit -r . -ll -iii --exit-zero -o bandit-report.txt -f txt || echo "Bandit scan completed with issues"
      
      # Explicitly use v4 to upload the artifact
      - name: Upload Bandit Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.txt

  container-and-dast-scan:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses:
