name: CI/CD Pipeline

# Trigger on push, pull request, or manually
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sca-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step 2: Install Dependencies for Safety Scan
      - name: Install Python dependencies
        run: |
          pip install safety
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "Error: requirements.txt not found!" && exit 1

      - name: Run Safety (SCA Scan)
        run: |
          safety check --file=requirements.txt --output text > safety-report.txt || echo "Safety scan completed with issues"
      
      - name: Verify Safety Report Exists
        run: |
          if [ -f "safety-report.txt" ]; then
            echo "Safety report generated successfully."
          else
            echo "Error: Safety report not found!" && exit 1
          fi

      - name: Upload Safety Report
        uses: actions/upload-artifact@v3
        with:
          name: safety-sca-report
          path: ./safety-report.txt


  sast-bandit:
    # needs: sca-trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Bandit (SAST Scan) and Generate HTML Report
        run: |
          pip install bandit
          bandit -r . -ll -iii -f html -o bandit-report.html || echo "Bandit scan completed with issues"

      - name: Verify Bandit HTML Report Exists
        run: |
          if [ -f "bandit-report.html" ]; then
            echo "Bandit HTML report generated successfully."
          else
            echo "Error: Bandit HTML report not found!" && exit 1
          fi

      - name: Upload Bandit HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-sast-html-report
          path: ./bandit-report.html
