name: CI/CD Pipeline

# Trigger on push, pull request, or manually
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  sca-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Safety
        run: |
          pip install safety

      - name: Run Safety with API Key
        run: |
          safety scan --file=requirements.txt --output html --save-html safety-report.html --key ${{ secrets.SAFETY_API_KEY }}

      - name: Verify Safety HTML Report Exists
        run: |
          if [ -f "safety-report.html" ]; then
            echo "Safety HTML report generated successfully."
          else
            echo "Error: Safety HTML report not found!" && exit 1
          fi

      - name: Upload Safety HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: safety-sca-html-report
          path: ./safety-report.html
