name: CI/CD Pipeline

# Trigger on push, pull request, or manually
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python 3.8
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check-6.5.3-release.zip -d dependency-check
          ls -alh dependency-check/

      - name: Run Dependency Check
        run: |
          ${GITHUB_WORKSPACE}/dependency-check/dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --out . --format HTML --failOnCVSS 9 --disableAssembly || echo "Vulnerabilities found"

      - name: Verify Dependency Check Report Exists
        run: |
          if [ -f "dependency-check-report.html" ]; then
            echo "Dependency Check report generated successfully."
          else
            echo "Error: Dependency Check report not found!" && exit 1
          fi

      # Upload the Dependency Check report as an artifact
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-artifact
          path: ./dependency-check-report.html

  sast:
    needs: dependency-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Bandit Scan
        run: |
          pip install bandit
          bandit -r . -ll -iii --exit-zero -o bandit-report.txt -f txt || echo "Bandit scan completed with issues"

      - name: Verify Bandit Report Exists
        run: |
          if [ -f "bandit-report.txt" ]; then
            echo "Bandit report generated successfully."
          else
            echo "Error: Bandit report not found!" && exit 1
          fi

      # Upload the Bandit report as an artifact
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-artifact
          path: ./bandit-report.txt

  deploy:
    needs: [dependency-check, sast]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Check for Symlinks (Recursive Search)
        run: |
          echo "Checking for symlinks across the workspace..."
          find . -type l -exec ls -lah {} \; || echo "No symlinks found."

      - name: Check for Hard Links
        run: |
          echo "Checking for hard links..."
          find . -type f -links +1 || echo "No hard links found."

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages-artifact
