name: CI/CD Pipeline

# Trigger pipeline on push, pull_request, and manual workflow_dispatch
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      # This step clears the cache of the runner for old actions and tools
      - name: Clear Runner Cache
        run: |
          echo "Clearing GitHub Runner Cache"
          rm -rf ${{ runner.tool_cache }}
          rm -rf ${{ runner.cache }}
          echo "Cache cleared"

  dependency-check:
    needs: setup  # Ensure cache is cleared before running the rest of the jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check-6.5.3-release.zip -d dependency-check
          ls -alh dependency-check/

      - name: Ensure script is executable
        run: chmod +x ${GITHUB_WORKSPACE}/dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run Dependency Check
        run: |
          ${GITHUB_WORKSPACE}/dependency-check/dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --out . --format HTML --failOnCVSS 9 --disableAssembly || echo "Vulnerabilities found"

      # Step to verify file presence
      - name: List Files in Directory
        run: ls -alh .

      # Explicitly use an exact version of v4 to upload the artifact
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4.0.2  # Explicitly pin exact version
        with:
          name: dependency-check-report
          path: dependency-check-report.html

  sast:
    needs: dependency-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.8'

      - name: Run Bandit Scan
        run: |
          pip install bandit
          bandit -r . -ll -iii --exit-zero -o bandit-report.txt -f txt || echo "Bandit scan completed with issues"

      # Explicitly use an exact version of v4 to upload the artifact
      - name: Upload Bandit Report as an Artifact
        uses: actions/upload-artifact@v4.0.2  # Explicitly pin exact version
        with:
          name: bandit-report
          path: bandit-report.txt

  container-and-dast-scan:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Build Docker Image
        run: |
          docker build -t pygoat:latest .
          docker images  # List images to confirm pygoat:latest is built

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pygoat:latest'

      - name: Run Docker Container with Command Override
        run: |
          docker run -d -p 8000:8000 --name pygoat-container pygoat:latest gunicorn -w 4 -b 0.0.0.0:8000 app:app
          sleep 10

      - name: Test Application is Running
        run: |
          curl -I http://localhost:8000 || (echo "Application failed to start" && docker logs pygoat-container && exit 1)

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'http://localhost:8000'
          docker_name: 'owasp/zap2docker-stable'
          report: true
          report_format: 'html'

      # Step to verify file presence before uploading
      - name: List Files in Directory
        run: ls -alh .

      # Explicitly use an exact version of v4 to upload the artifact
      - name: Upload Reports
        uses: actions/upload-artifact@v4.0.2  # Explicitly pin exact version
        with:
          name: scan-reports
          path: |
            trivy-report.json
            zap-report.html

      - name: Stop and Remove Docker Container
        run: |
          docker stop pygoat-container
          docker rm pygoat-container
