name: CI/CD Pipeline

# Trigger on push, pull request, or manually
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  sca-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Safety
        run: |
          pip install safety

      - name: Run Safety (SCA Scan) and Generate HTML Report
        run: |
          safety check --file=requirements.txt --output safety-report.html

      - name: Verify Safety HTML Report Exists
        run: |
          if [ -f "safety-report.html" ]; then
            echo "Safety HTML report generated successfully."
          else
            echo "Error: Safety HTML report not found!" && exit 1
          fi

      # Upload the Safety HTML report as an artifact
      - name: Upload Safety HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: safety-sca-html-report
          path: ./safety-report.html

  sast-bandit:
    needs: sca-safety
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Bandit (SAST Scan) and Generate HTML Report
        run: |
          pip install bandit
          bandit -r . -ll -iii -f html -o bandit-report.html || echo "Bandit scan completed with issues"

      - name: Verify Bandit HTML Report Exists
        run: |
          if [ -f "bandit-report.html" ]; then
            echo "Bandit HTML report generated successfully."
          else
            echo "Error: Bandit HTML report not found!" && exit 1
          fi

      # Upload the Bandit HTML report as an artifact
      - name: Upload Bandit HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-sast-html-report
          path: ./bandit-report.html
