name: CI/CD Pipeline

# Trigger on push, pull request, or manually
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python 3.8
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check-6.5.3-release.zip -d dependency-check
          ls -alh dependency-check/

      - name: Run Dependency Check
        run: |
          ${GITHUB_WORKSPACE}/dependency-check/dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --out . --format HTML --failOnCVSS 9 --disableAssembly || echo "Vulnerabilities found"

      - name: List Files in Directory
        run: ls -alh .

      # Upload the Dependency Check report as an artifact
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v3  # Use upload-artifact to handle single files
        with:
          name: pages-artifact  # Give the artifact a name
          path: ./dependency-check-report.html  # Specify the report path

  sast:
    needs: dependency-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Bandit Scan
        run: |
          pip install bandit
          bandit -r . -ll -iii --exit-zero -o bandit-report.txt -f txt || echo "Bandit scan completed with issues"

      # Upload the Bandit report as an artifact
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3  # Use upload-artifact to handle single files
        with:
          name: pages-artifact  # Give the artifact a name
          path: ./bandit-report.txt  # Specify the Bandit report path

  deploy:
    needs: [dependency-check, sast]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact-name: pages-artifact
