name: Container Scanning
on: [push, pull_request]
jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t pygoat:latest .
    - name: Scan Docker Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'pygoat:latest'
    - name: Upload Trivy scan report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report.json
