name: DAST
on: [push, pull_request]
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Check Docker
        run: |
          docker info
          docker ps
  
      - name: Start Application
        run: |
          docker-compose up -d
          docker-compose logs
  
      - name: Wait for application to be ready
        run: |
          max_retries=60
          retries=0
          until curl -sSf http://localhost:8000 > /dev/null || [ $retries -eq $max_retries ]
          do
            echo "Waiting for application to be ready..."
            sleep 5
            retries=$((retries+1))
          done
          if [ $retries -eq $max_retries ]; then
            echo "Application failed to start in time"
            docker-compose logs
            exit 1
          fi
  
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:8000'
          docker_name: 'owasp/zap2docker-stable'
