name: DAST
on: [push, pull_request]
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Set up directory permissions
        run: |
          sudo mkdir -p ./data/db
          sudo chown -R 1000:1000 ./data/db
          sudo chmod -R 777 ./data/db

      - name: Build Docker image
        run: docker build -t pygoat/pygoat .


      - name: Start database
        run: |
          docker network create pygoat_network
          docker run -d --name pygoat_db --network pygoat_network \
            -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres \
            -v $PWD/data/db:/var/lib/postgresql/data postgres

      - name: Run migrations
        run: |
          docker run --rm --network pygoat_network \
            -v $PWD:/app -w /app pygoat/pygoat \
            python manage.py migrate --noinput

      - name: Start web application
        run: |
          docker run -d --name pygoat_web --network pygoat_network \
            -p 8000:8000 -v $PWD:/app -w /app pygoat/pygoat \
            sh -c "pip install gunicorn && python -m gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi"

      - name: Check running containers
        run: docker ps


      - name: Check web container logs
        run: docker logs pygoat_web
      
        
      - name: Wait for application to be ready
        run: |
          max_retries=60
          retries=0
          until curl -sSf http://localhost:8000 > /dev/null || [ $retries -eq $max_retries ]
          do
            echo "Waiting for application to be ready..."
            sleep 5
            retries=$((retries+1))
          done
          if [ $retries -eq $max_retries ]; then
            echo "Application failed to start in time"
            docker-compose logs
            exit 1
          fi
  
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:8000'
          docker_name: 'owasp/zap2docker-stable'
  
      - name: Cleanup
        if: always()
        run: docker-compose down -v
