name: DAST
on: [deployment]
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start Application
      run: docker-compose up -d
    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
        target: 'http://localhost:8000'
