name: SAST
on: [push, pull_request]
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Run Bandit Scan
      run: |
        pip install bandit
        bandit -r . -ll -iii --exit-zero -o bandit-report.txt -f txt || echo "Bandit scan completed with issues"
    - name: Upload Bandit Report as an Artifact
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: bandit-report.txt
